# YAML pipeline for building Java program and running Python code
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      javac HelloWorld.java
      java HelloWorld

- script: |
    python your_python_script.py
  displayName: 'Run Python script'
